/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#f0f1f2',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'tertiary-fixed-dim': '#ffb68b',
        'on-tertiary-fixed-variant': '#753400',
        'secondary-fixed-dim': '#ffb955',
        'on-secondary-container': '#6b4500',
        'surface-bright': '#f8f9fa',
        'tertiary-fixed': '#ffdbc8',
        'on-background': '#191c1d',
        'on-primary': '#ffffff',
        'surface-container-high': '#e7e8e9',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed': '#321200',
        'primary-fixed-dim': '#d2bcff',
        'on-surface': '#191c1d',
        'tertiary': '#6d3000',
        'inverse-primary': '#d2bcff',
        'on-surface-variant': '#4a4455',
        'outline-variant': '#ccc3d7',
        'primary-container': '#6c2bd9',
        'error': '#ba1a1a',
        'secondary-container': '#feae2c',
        'on-primary-fixed-variant': '#5900c7',
        'surface': '#f8f9fa',
        'on-tertiary-container': '#ffc3a1',
        'secondary': '#835500',
        'primary-fixed': '#eaddff',
        'on-secondary-fixed': '#291800',
        'secondary-fixed': '#ffddb4',
        background: '#f8f9fa',
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#633f00',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#25005a',
        'surface-container-highest': '#e1e3e4',
        'inverse-surface': '#2e3132',
        'surface-dim': '#d9dadb',
        'on-primary-container': '#dac7ff',
        'surface-variant': '#e1e3e4',
        'surface-container': '#edeeef',
        'surface-tint': '#7233df',
        'on-error': '#ffffff',
        primary: '#5300b9',
        'tertiary-container': '#914200',
        outline: '#7b7486',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans'],
        body: ['Inter'],
        label: ['Inter'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};